apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    env: prod
    proj: flux-suspension-exporter
  name: flux-suspension-exporter-env-configmap
  namespace: monitoring
data:
  LOG_LEVEL: "debug"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flux-suspension-exporter
  name: flux-suspension-exporter
  namespace: monitoring
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: flux-suspension-exporter
      proj: flux-suspension-exporter
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
        prometheus.istio.io/merge-metrics: "false"
      labels:
        app: flux-suspension-exporter
        proj: flux-suspension-exporter
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: flux-suspension-exporter-env-configmap
          image: flux-suspension-exporter:dev
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: metrics
            initialDelaySeconds: 3
            periodSeconds: 3
          name: flux-suspension-exporter
          ports:
            - containerPort: 8081
              name: metrics
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: metrics
            periodSeconds: 5
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
